name: C++ Build/Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: TDD permissions
      run: chmod +x TDD.sh
    - name: TDD check
      run: ./TDD.sh
