name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
      defaults:
      run:
        shell: zsh {0}

    steps:
    - uses: actions/checkout@v3
    - name: TDD
      run: ./Binarytree/CPP/TDD.sh
