name: TDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Binary_Search_Tree:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: TDD permissions
      run: chmod +x ./Binarytree/CPP/TDD.sh
    - name: TDD check BST
      run: (cd ./Binarytree/CPP/ && ./TDD.sh)
  Stack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: TDD permissions
      run: chmod +x ./Stack/CPP/TDD.sh
    - name: TDD check Stack
      run: (cd ./Stack/CPP/ && ./TDD.sh)
